version: '3.8'
services:
  techofmany-base:
    build:
      context: .
    image: ${CONTAINER_REGISTRY}/k8s-techofmany:${VERSION}
  k8s-techofmany:
    image: ${CONTAINER_REGISTRY}/k8s-techofmany:${VERSION}
    command: npm run start -w site
    ports:
      - 3001:3001
  k8s-techofmany-admin:
    image: ${CONTAINER_REGISTRY}/k8s-techofmany:${VERSION}
    command: npm run start -w admin
    ports:
      - 4001:4001
